spring:
  application:
    name: {{.ArtifactID}}

server:
  port: {{.Port}}

lark:
  project: 
    type: msg-handler

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
---
spring:
  config:
    activate:
      on-profile: playground

lark:
  registry:
    address: register-dev.lark-cloud.com:8848

  msg:
    address: mq-dev.lark-cloud.com:9876
    subscriber: true